### ISSUE TITLE
scripting interface

### ISSUE THREAD

**Issue by schtobia** [AbstractStateMachine/concept#3]
As we don't want to repeat old mistakes, we want a clean and usable command line interface - mostly for debugging purposes.

## The alternatives

* [Boost.Python](http://www.boost.org/doc/libs/release/libs/python/doc/html/index.html)
  * not threadsafe
  * well-known scripting language
  * maybe higher memory footprint?
* [Lua](https://github.com/cslarsen/lua-cpp)
  * small footprint
  * new scripting language
  * threadsafe
* [SpiderMonkey](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey)
  * new scripting language
  * threadsafe
  * not exactly lightweight
* [V8](https://github.com/v8/v8/)
  * heavyweight
  * new scripting language
    * but the best-known JS engine!
  * not threadsafe

**Comment by BorisSchaeling** [comment]
If you are interested in a Python interface: There is a modern C++ Boost.Python alternative called pybind11 (see https://github.com/pybind/pybind11). This project is maintained very well (actually better than Boost.Python). 

I happen to work on an automated Python API generator (based on pybind11). It is a command line utility you pass a C or C++ header file to. And it automatically generates the required Python API. While the tool is in an early stage, it could still be sufficient (especially if the API should "only" be used for debugging purposes). Besides, I would be happy for any user feedback. :)

**Comment by schtobia** [comment]
> I happen to work on an automated Python API generator (based on pybind11). It is a command line utility you pass a C or C++ header file to.

Great! Is this generator available somewhere in the public space?

**Comment by BorisSchaeling** [comment]
It's not available yet (still too much under construction :). That said maybe it's easier if we turn it around for now: If you let me know which header file(s) I should use to generate the Python API, I can give it a try. If the generator outputs code which looks reasonable and compiles, I can forward the output to you?

**Comment by schtobia** [comment]
We're not that far yet, as there are other project at present. But once this is done, I'd love to look over this!

**Comment by BorisSchaeling** [comment]
That's great! I hope I'll have made some more progress until then and can provide something more complete than what I have right now. :)

**Comment by ReinhardProbst** [comment]
We have a cpp file for pybind11, if you want:
https://github.com/AsynchronousMachine/concept/blob/master/src/maker/maker_reflection.cpp
Actually we using a JSON based interface, e.g. to access this in maker_reflection.cpp (line 45):
```
const name_dataobject_map name_dataobjects {
	{"InputModule.inModule.DOintOutput", inModule.DOintOutput},

}
```
we encode it to:
`{"InputModule.inModule.DOintOutput":100}`
parse it, extract the key and hand over the value.
Refer to https://github.com/AsynchronousMachine/concept/blob/master/src/communication/ReceiveHandler.cpp (line 52).
To read out that value we use:
`{"InputModule.inModule.DOintOutput":null}`.
